# general settings 
results_folder_name: CODEX7to3_demo_results

# data settings
imaging_platform: CODEX # [CODEX | MIBI], select imaging platform
test_dataset_path: datasets/Test_CODEX_7to3_demo_dataset # path to test set folder
compression_matrix_form_path: compression_matrices/CODEX_7to3_real_to_real.csv  # path to compression matrices form
center_crop: 768 # Empty for whole image or number of pixels

# inference settings
masking_models_folder: pretrained_models/CODEX_7to3_demo/binary # path to decompression masking models folder to use for inference
values_reconstruction_models_folder: pretrained_models/CODEX_7to3_demo/values # path to value reconstruction models folder to use for inference
agreement: 0.5 # agreement fraction for positive classification
evaluate_with_GT: True # [True | False]










