model_name:
W&B_entity: 
seed: # [empty | num in (0, 2 ** 32)], Leave empty for random seed or set a number
imaging_platform: # [CODEX | MIBI], select imaging platform for simulation
training_dataset_path: # path to training set folder
validation_dataset_path: # path to validation set folder
compression_matrix_form_path:  # path to compression matrices form

Decompression masking network:
  noise_parameters: [0, 0, 0, 0] # noise parameters [n1, n2, n3, n4] as in the methods section
  num_batches: 200000 # set upper limit number of baches for training
  running_time: 11.8 # max training time; checkpoint will be saved before exit
  batch_size: 4 # recommended: 4
  crop_size: 512 # recommended: 512
  dropout_rate: 0 # num in (0, 1)
  lr: 0.0001 # recommended: 0.0001
  validation_frequency: 20 # validation epoch frequency
  save_checkpoint_frequency: 10000 # checkpoint frequency
  model_features: [64, 128, 128, 256, 256] # recommended: [64, 128, 128, 256, 256]

Value reconstruction network:
  noise_parameters: [0, 0, 0, 0] # noise parameters [n1, n2, n3, n4] as in the methods section
  num_batches: 200000 # set upper limit number of baches for training
  running_time: 11.8 # max training time; checkpoint will be saved before exit
  batch_size: 4 # recommended: 4
  crop_size: 512 # recommended: 512
  dropout_rate: 0 # num in (0, 1)
  lr: 0.0001 # recommended: 0.0001
  validation_frequency: 20 # validation epoch frequency
  save_checkpoint_frequency: 10000 # checkpoint frequency
  model_features: [64, 128, 128, 256, 256] # recommended: [64, 128, 128, 256, 256]